// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckCredentials():Promise<boolean>;

export function GetSpecs():Promise<main.PCSpecs>;

export function InstallToPC():Promise<string>;

export function SaveConfig(arg1:string,arg2:string,arg3:string):Promise<string>;
